-- MySQL Script generated by MySQL Workbench
-- Sat Apr  6 10:19:54 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ecobabyplanet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecobabyplanet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecobabyplanet` ;
USE `ecobabyplanet` ;

-- -----------------------------------------------------
-- Table `ecobabyplanet`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecobabyplanet`.`rol` (
  `idrol` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `rol` ENUM('registrado', 'administrador') NOT NULL COMMENT '',
  PRIMARY KEY (`idrol`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecobabyplanet`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecobabyplanet`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(30) NOT NULL COMMENT '',
  `apellidos` VARCHAR(50) NOT NULL COMMENT '',
  `movil` VARCHAR(20) NOT NULL COMMENT '',
  `fecha_nacimiento` DATETIME NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `contrasena` VARCHAR(64) NOT NULL COMMENT '',
  `fecha_creacion` DATETIME NOT NULL COMMENT '',
  `direccion` VARCHAR(50) NOT NULL COMMENT '',
  `dni` VARCHAR(10) NOT NULL COMMENT '',
  `id_rol` INT(11) NOT NULL COMMENT '',
  `rol_idrol` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_usuario`)  COMMENT '',
  INDEX `fk_usuario_rol_idx` (`rol_idrol` ASC)  COMMENT '',
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`rol_idrol`)
    REFERENCES `ecobabyplanet`.`rol` (`idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecobabyplanet`.`suscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecobabyplanet`.`suscripcion` (
  `id_suscripcion` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_usuario` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(20) NOT NULL COMMENT '',
  `descripcion` VARCHAR(50) NOT NULL COMMENT '',
  `imagen` VARCHAR(45) NOT NULL COMMENT '',
  `precio` DECIMAL(3,2) NOT NULL COMMENT '',
  `divisa` VARCHAR(3) NOT NULL COMMENT '',
  PRIMARY KEY (`id_suscripcion`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecobabyplanet`.`usuario_compra_suscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecobabyplanet`.`usuario_compra_suscripcion` (
  `id_usuario` INT NOT NULL COMMENT '',
  `id_suscripcion` INT NOT NULL COMMENT '',
  `fecha_compra` DATETIME NOT NULL COMMENT '',
  `fecha_expiracion` DATE NOT NULL COMMENT '',
  PRIMARY KEY (`id_usuario`)  COMMENT '',
  INDEX `uhuuu_idx` (`id_suscripcion` ASC)  COMMENT '',
  CONSTRAINT `FK_USUARIO_SUSCRIPCION_SUSCRIPCION`
    FOREIGN KEY (`id_suscripcion`)
    REFERENCES `ecobabyplanet`.`suscripcion` (`id_suscripcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_USUARIO_SUSCRIPCION_USUARIO`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ecobabyplanet`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecobabyplanet`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecobabyplanet`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_suscripcion` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `descripcion` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_producto`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecobabyplanet`.`suscripcion_tiene_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecobabyplanet`.`suscripcion_tiene_producto` (
  `id_producto` INT NOT NULL COMMENT '',
  `id_suscripcion` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_producto`, `id_suscripcion`)  COMMENT '',
  INDEX `FK_SUSCRIPCION_SUSCRIPCIONTIENEPRODUCTO_idx` (`id_suscripcion` ASC)  COMMENT '',
  CONSTRAINT `FK_SUSCRIPCION_SUSCRIPCIONTIENEPRODUCTO`
    FOREIGN KEY (`id_suscripcion`)
    REFERENCES `ecobabyplanet`.`suscripcion` (`id_suscripcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PRODUCTO_SUSCRIPCIONTIENEPRODUCTO`
    FOREIGN KEY (`id_producto`)
    REFERENCES `ecobabyplanet`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
